<?php

namespace frontend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "request".
 *
 * @property int $request_id
 * @property int $first_name
 * @property int $last_name
 * @property int $vacancy_id
 * @property int $created_by
 * @property string $created_at
 * @property int $status
 * @property string $resume
 *
 * @property User $createdBy
 * @property Vacancy[] $vacancies
 */
class Request extends \yii\db\ActiveRecord
{
    public $resumeFile;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'request';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'vacancy_id'], 'required'],
            [['vacancy_id'], 'integer'],
            [['first_name', 'last_name'], 'string'],
            [['email'], 'email'],
            [['resumeFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'docx, pdf'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'request_id' => 'Request ID',
            'first_name' => 'Ім\'я',
            'last_name' => 'Прізвище',
            'email' => 'Email',
            'resume' => 'Резюме',
            'created_at' => "Час створення",
            'vacancy' => "Вакансія",
            'username' => "Ким створено"
        ];
    }

    public function loadParams()
    {
        $user = User::findOne(Yii::$app->user->getId());
        $this->first_name = $user->first_name;
        $this->last_name = $user->last_name;
        $this->email = $user->email;
    }

    public function getFolder()
    {
        return Yii::getAlias("@frontend") . '/web/resume/';
    }

    public function uploadResume()
    {
        if ($this->resumeFile->saveAs($this->getFolder() . $this->resume)) {
            return true;
        }
        return null;
    }

    public function getResumeLink()
    {
        if (!is_file(Yii::getAlias("@frontend") . '/web/resume/' . $this->resume)) {
            return '#';
        }
        return '/resume/' . $this->resume;
    }



    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    public function getUsername()
    {
        return $this->user->username;
    }

    /**
     * Gets query for [[Vacancies]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVacancy()
    {
        return $this->hasOne(Vacancy::className(), ['vacancy_id' => 'vacancy_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_at = Date("Y-m-d h:i:s");
            $this->status = 1;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
