<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "request".
 *
 * @property int $request_id
 * @property int $first_name
 * @property int $last_name
 * @property int $vacancy_id
 * @property int $created_by
 * @property string $created_at
 * @property int $status
 * @property string $resume
 *
 * @property User $createdBy
 * @property Vacancy[] $vacancies
 */
class Request extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'request';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'vacancy_id'], 'required'],
            [['vacancy_id'], 'integer'],
            [['first_name', 'last_name'], 'string'],
            [['email'], 'email'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'request_id' => 'Request ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'resume' => 'Resume',
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    public function getUsername()
    {
        return $this->user->username;
    }

    /**
     * Gets query for [[Vacancies]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVacancy()
    {
        return $this->hasOne(Vacancy::className(), ['vacancy_id' => 'vacancy_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_at = Date("Y-m-d h:i:s");
            $this->status = 1;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
